Controllers/AdminColorController.cs
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System;
using Camisetas.Infrastructure.Filters;
using Camisetas.Infrastructure;
using Camisetas.Models.ViewModels;
using Camisetas.Models;
using Camisetas.DAL;

namespace Camisetas.Controllers
{
    [RepositoryExceptionFilter]
    public class AdminColorController : Controller
    {
        // Fields
        private IColorRepository colorRepository;

        // Ctor
        public AdminColorController(IColorRepository color)
            => this.colorRepository = color;

        // Methods

        [HttpGet]
        public ViewResult ColorList(int pageNumber = 1, int itemsPerPage = 4) 
            => View(new GenericListViewModel<Color>()
            {
                CollectionToSend = colorRepository.Colors
                    .Skip((pageNumber - 1 ) * itemsPerPage )
                    .Take(itemsPerPage),
                PagingInfo = new PagingInfo(){
                    CurrentPage = pageNumber,
                    ItemsPerPage = itemsPerPage,
                    TotalItems = colorRepository.Colors.Count()
                }
            });

        [HttpGet]
        public ViewResult CreateColor() 
            => View(new Color());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateColor(
                [FromForm]Color color)
        {
            if(ModelState.IsValid)
            {
                colorRepository.SaveColor(color);
                TempData["SuccessMessage"] = 
                    $"{color.Name} color ({color.Id}) was successfully created";
                return View(new Color());
            }
            else{ return View(color); }
        } // End of method CreateColor.


        [HttpGet]
        public ViewResult EditColor(Guid id) =>
            View((colorRepository[id]) != null ? 
                colorRepository[id]
                : throw new ArgumentNullException(nameof(id),
                    "Unable to find color to edit") );



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditColor(Color color)
        {
            if(ModelState.IsValid)
            {
                colorRepository.SaveColor(color);
                TempData["SuccessMessage"] = $"{color.Name} color ({color.Id})"
                + " was successfully edited";
                return View();
            }else{
                return View(color);
            }
        } // End of method EditColor.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteColor([FromForm]Guid colorId)
        {
            if(colorId != null)
            {
                Color color = colorRepository.DeleteColor(colorId);
                if(color != null)
                {
                    TempData["SuccessMessage"] = 
                    $"{color.Name} ({color.Id}) was deleted";
                    return RedirectToAction(nameof(ColorList));
                }else{
                    TempData["WarningMessage"] = $"Unable to delete {colorId} ";
                    return RedirectToAction(nameof(ColorList));
                }
            }else{
                TempData["ErrorMessage"] = 
                    $" Sorry, an unexpected error ocurred when deleting item";
                return RedirectToAction(nameof(ColorList));
            }
        } // End of method DeleteColor.

    } // End of class AdminColorController.

} // End of namespace Camisetas.Controllers.

Controllers/AdminSizeController.cs
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System;
using Camisetas.Infrastructure.Filters;
using Camisetas.Infrastructure;
using Camisetas.Models.ViewModels;
using Camisetas.Models;
using Camisetas.DAL;

namespace Camisetas.Controllers
{
    [RepositoryExceptionFilter]
    public class AdminSizeController : Controller
    {
        // Fields
        private ISizeRepository sizeRepository;

        // Ctor
        public AdminSizeController(ISizeRepository repo) => sizeRepository = repo;

        [HttpGet]
        public ViewResult SizeList(int pageNumber = 1, int itemsPerPage = 4) 
            => View(new GenericListViewModel<Size>()
            {
                CollectionToSend = sizeRepository.Sizes
                    .Skip((pageNumber - 1) * itemsPerPage)
                    .Take(itemsPerPage),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = pageNumber,
                    TotalItems = sizeRepository.Sizes.Count(),
                    ItemsPerPage = itemsPerPage
                }
            });

        [HttpGet]
        public ViewResult CreateSize() => View(new Size());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSize([FromForm]Size size)
        {
            if(ModelState.IsValid)
            {
                sizeRepository.SaveSize(size);
                TempData["SuccessMessage"] = 
                    $"{size.Name} ({size.Id}) was successfully created";
                return View(new Size());
            }
            else{ return View(size); }
        } // End of method CreateSize

        [HttpGet]
        public ViewResult EditSize(Guid id) =>
            View((sizeRepository[id]) != null ? 
                sizeRepository[id]
                : throw new ArgumentNullException(nameof(id),
                    "Unable to find size to edit") );



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSize(Size size)
        {
            if(ModelState.IsValid)
            {
                sizeRepository.SaveSize(size);
                TempData["SuccessMessage"] = $"{size.Name} ({size.Id})"
                + " was successfully edited";
                return View();
            }else{
                return View(size);
            }
        } // End of method EditColor.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteSize([FromForm]Guid sizeId)
        {
            if(sizeId != null)
            {
                Size size = sizeRepository.DeleteSize(sizeId);
                if(size != null)
                {
                    TempData["SuccessMessage"] = 
                    $"{size.Name} size ({size.Id}) was deleted";
                    return RedirectToAction(nameof(SizeList));
                }else{
                    TempData["WarningMessage"] = $"Unable to delete {sizeId} ";
                    return RedirectToAction(nameof(SizeList));
                }
            }else{
                TempData["ErrorMessage"] = 
                    $" Sorry, an unexpected error ocurred when deleting item";
                return RedirectToAction(nameof(SizeList));
            }
        } // End of method DeleteColor.

    } // End of class AdminSizeController.

} // End of namespace Camisetas.Controllers.

Controllers/AdminTshirtController.cs
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System;
using Camisetas.Infrastructure.Filters;
using Camisetas.Infrastructure;
using Camisetas.Models.ViewModels;
using Camisetas.Models;
using Camisetas.DAL;

namespace Camisetas.Controllers
{
    [RepositoryExceptionFilter]
    public class AdminTshirtController : Controller
    {
        // Fields
        private ITshirtRepository tshirtRepository;
        private IColorRepository colorRepository;
        private ISizeRepository sizeRepository;
        private IClothingRepository clothingRepository;
        private ITypeRepository typeRepository;

        // Ctor.
        public AdminTshirtController(ITshirtRepository tshirtRepo,
            IColorRepository colorRepo,
            ISizeRepository sizeRepo,
            IClothingRepository clothingRepo,
            ITypeRepository typeRepo)
            {
                this.tshirtRepository = tshirtRepo;
                this.colorRepository = colorRepo;
                this.sizeRepository = sizeRepo;
                this.clothingRepository = clothingRepo;
                this.typeRepository = typeRepo;
            } 
        

        // Methods
        [HttpGet]
        public IActionResult Index( int pageNumber = 1, int itemsPerPage = 4)
        => View(new GenericListViewModel<Tshirt>()
                    {
                        CollectionToSend = tshirtRepository.Tshirts
                                .OrderBy(t => t.Id)
                                .Skip((pageNumber - 1) * itemsPerPage)
                                .Take(itemsPerPage),
                        PagingInfo = new PagingInfo()
                        {
                            ItemsPerPage = itemsPerPage,
                            TotalItems = tshirtRepository.Tshirts.Count(),
                            CurrentPage = pageNumber
                        }
                    });

        [HttpGet]
        public ViewResult Create()
        {
            return View(new TshirtViewModel());
        } // End of method Create.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm]TshirtViewModel tshirtModel)
        {
            if(ModelState.IsValid)
            {
                Tshirt tshirt = ConvertToTshirt(tshirtModel);
                tshirtRepository.SaveTshirt(tshirt);
                TempData["SuccessMessage"] = $"{tshirt.Name} "
                +$"tshirt ({tshirt.Id}) "
                +"was successfully created";
                return RedirectToAction(nameof(Create));
            }else{
                return View(tshirtModel);    
            }
        } // End of method Create.

        [HttpGet]
        public ViewResult Edit (Guid id) 
            => View( (tshirtRepository[id]) != null ? 
                ConvertToTshirtViewModel(tshirtRepository[id])
                : throw new ArgumentException(nameof(id),
                    "Unable to find color to edit"));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TshirtViewModel tshirtModel)
        {
            if(ModelState.IsValid)
            {
                tshirtRepository.SaveTshirt( ConvertToTshirt(tshirtModel));
                TempData["SuccessMessage"] = $"{tshirtModel.Name} ({tshirtModel.Id}) "
                +"was successfully edited";
                return RedirectToAction(nameof(Edit));
            } else{
                return View(tshirtModel);
            }
        } // End of method Edit

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Delete ([FromForm]Guid tshirtId)
        {
            if(tshirtId != null)
            {
                Tshirt tshirt =  tshirtRepository.DeleteTshirt(tshirtId);
                if(tshirt != null)
                {
                    TempData["SuccessMessage"] = $"{tshirt.Name} ({tshirt.Id}) was deleted";
                    return RedirectToAction(nameof(Index));
                }else{
                    TempData["WarningMessage"] = $"Unable to delete {tshirtId} ";
                    return RedirectToAction(nameof(Index));
                }
            }else{
                TempData["ErrorMessage"] = $" Sorry, an unexpected error ocurred when deleting item";
                return RedirectToAction(nameof(Index));
            }
        } // End of method Delete
        private TshirtViewModel ConvertToTshirtViewModel(Tshirt tshirt)
        {
            TshirtViewModel tshirtViewModel = new TshirtViewModel()
            {
                Id = tshirt.Id,
                Name = tshirt.Name,
                Price = tshirt.Price,
                Size = tshirt.Size.Id,
                Type = tshirt.Type.Id,
                Color = tshirt.Color.Id,
                Clothing = tshirt.Clothing.Id,
                Width = tshirt.Width,
                Height = tshirt.Height
            };
            return tshirtViewModel;
        }

        private Tshirt ConvertToTshirt(TshirtViewModel tshirtViewModel)
        {
            Tshirt tshirt = tshirtRepository[tshirtViewModel.Id];
            tshirt = tshirt is null ? new Tshirt() : tshirt;

            tshirt.Name = tshirtViewModel.Name;
            tshirt.Price = tshirtViewModel.Price;
            tshirt.Width = tshirtViewModel.Width;
            tshirt.Height = tshirtViewModel.Height;

            tshirt.Size = tshirt.Size is null  || 
                tshirt.Size.Id != tshirtViewModel.Size ?
                sizeRepository[tshirtViewModel.Size] : tshirt.Size;

            tshirt.Type = tshirt.Type is null ||
                tshirt.Type.Id != tshirtViewModel.Type ?
                typeRepository[tshirtViewModel.Type] : tshirt.Type;

            tshirt.Color = tshirt.Color is null ||
                tshirt.Color.Id != tshirtViewModel.Color ?
                colorRepository[tshirtViewModel.Color] : tshirt.Color;

            tshirt.Clothing = tshirt.Clothing is null ||
                tshirt.Clothing.Id != tshirtViewModel.Clothing ?
                clothingRepository[tshirtViewModel.Clothing] : tshirt.Clothing;
                
            return tshirt;
        } // End of method ConvertToTshirt.

    } // End of class HomeController.

} // End of namespace Camisetas.Controllers.tshirtViewModel.

Controllers/AdminTypeController.cs
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System;
using Camisetas.Infrastructure.Filters;
using Camisetas.Infrastructure;
using Camisetas.Models.ViewModels;
using Camisetas.Models;
using Camisetas.DAL;

namespace Camisetas.Controllers
{
    [RepositoryExceptionFilter]
    public class AdminTypeController : Controller
    {
        // Fields
        private ITypeRepository typeRepository;

        // Ctor
        public AdminTypeController (ITypeRepository  repo)
            => typeRepository = repo;

        [HttpGet]
        public ViewResult TypeList(int pageNumber = 1, int itemsPerPage = 4)
            => View(new GenericListViewModel<Models.Type>()
            {
                CollectionToSend = typeRepository.Types
                    .Skip((pageNumber - 1) * itemsPerPage)
                    .Take(itemsPerPage),
                PagingInfo =  new PagingInfo()
                {
                    CurrentPage = pageNumber,
                    ItemsPerPage = itemsPerPage,
                    TotalItems = typeRepository.Types.Count()
                }
            });

        [HttpGet]
        public ViewResult CreateType() => View(new Models.Type());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateType([FromForm]Models.Type type)
        {
            if(ModelState.IsValid)
            {
                typeRepository.SaveType(type);
                TempData["SuccessMessage"] = 
                    $"{type.Name} type ({type.Id}) was successfully created";
                return View(new Models.Type());
            }
            else{ return View(type); }
        } // End of method CreateType.

        [HttpGet]
        public ViewResult EditType(Guid id) =>
            View((typeRepository[id]) != null ? 
                typeRepository[id]
                : throw new ArgumentNullException(nameof(id),
                    "Unable to find size to edit") );
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditType(Models.Type type)
        {
            if(ModelState.IsValid)
            {
                typeRepository.SaveType(type);
                TempData["SuccessMessage"] = $"{type.Name} type ({type.Id})"
                + " was successfully edited";
                return View();
            }else{
                return View(type);
            }
        } // End of method EditColor.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteType([FromForm]Guid typeId)
        {
            if(typeId != null)
            {
                Models.Type type = typeRepository.DeleteType(typeId);
                if(type != null)
                {
                    TempData["SuccessMessage"] = 
                    $"{type.Name} type ({type.Id}) was deleted";
                    return RedirectToAction(nameof(TypeList));
                }else{
                    TempData["WarningMessage"] = $"Unable to delete {typeId} ";
                    return RedirectToAction(nameof(TypeList));
                }
            }else{
                TempData["ErrorMessage"] = 
                    $" Sorry, an unexpected error ocurred when deleting item";
                return RedirectToAction(nameof(TypeList));
            }
        } // End of method DeleteColor.
        
    } // End of class AdminTypeRepository.

} // End of namespace Camisetas.Controllers.

Views/Shared/AlertMessagesPartialView.cshtml
        @if(TempData["SuccessMessage"] != null)
        {
            string message = (string) TempData["SuccessMessage"];
            <div style="font-size:2.1em;" class=" alert alert-success text-xl-center alert-dismissible fade show" role="alert" >
                @message
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        @if(TempData["WarningMessage"] != null)
        {
            string message = (string) TempData["WarningMessage"];
            <div style="font-size:2.1em;" class=" alert alert-warning text-xl-center alert-dismissible fade show" role="alert" >
                @message
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        @if(TempData["ErrorMessage"] != null)
        {
            string message = (string) TempData["ErrorMessage"];
            <div style="font-size:2.1em;" class=" alert alert-danger text-xl-center alert-dismissible fade show" role="alert" >
                @message
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Example WEB application" />
        <meta name="keywords" content="Example WEB application" />
        <meta name="author" content="Matheus Alves Lima" />
        <title>@ViewBag.Title</title>
        <style>
            .field-validation-error
            {
                color: red;
            }
        </style>
        <environment names="development" >
            <link type="text/css" rel="stylesheet" 
            asp-href-include="~/lib/bootstrap-4.1.3/dist/**/bootstrap.css" />
            <link type="text/css" rel="stylesheet" asp-href-include="~/**/Custom.css" />
            <script type="application/javascript" defer="defer" 
            asp-src-include="~/lib/jquery/dist/jquery.js" ></script>
            <script type="application/javascript" defer="defer" 
            asp-src-include="~/lib/popper.js/dist/umd/popper.js" ></script>
            <script type="application/javascript" defer="defer" 
            asp-src-include="~/lib/bootstrap-4.1.3/dist/**/bootstrap.js" ></script>
        </environment>
        <environment names="production" >
            <link type="text/css" rel="stylesheet" asp-href-include="~/lib/bootstrap/dist/**/*.min.css"
                asp-href-exclude=""    >
        </environment>  
    </head>
    <body>
        
        <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
            <a class="navbar-brand" asp-action="Index" asp-route-pagenumber="1" 
                asp-controller="AdminTshirt" >T-shirts
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" 
                data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" 
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav" >
                    <li class="nav-item" >
                        <div class="dropdown ">
                            <button type="button" class="btn dropdown-toggle" id="dropdownMenuOffset" 
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" 
                                data-offset="10,20">
                            T-shirt properties
                            </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                                <a class="dropdown-item" asp-controller="AdminColor"
                                    asp-action="ColorList"  >Color Property</a>
                                <a class="dropdown-item" asp-controller="AdminSize"
                                    asp-action="SizeList" >Size Property</a>
                                <a class="dropdown-item" asp-controller="AdminType"
                                    asp-action="TypeList" >Type Property</a>
                                <a class="dropdown-item" asp-controller="AdminClothing"
                                    asp-action="ClothingList" >Clothing Property</a>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item" ><a href="#" class="nav-link" >PLACE HOLDER</a></li>
                    <li class="nav-item" ><a href="#" class="nav-link" >PLACE HOLDER</a></li>
                    <li class="nav-item" ><a href="#" class="nav-link" >PLACE HOLDER</a></li>
                    <li class="nav-item" ><a href="#" class="nav-link" >PLACE HOLDER</a></li>
                </ul>
            </div>
        </nav>
        @await Html.PartialAsync("AlertMessagesPartialView")
        <br/>
        <br/>

        @RenderBody()

        <br/>
        <br/>
    </body>
</html>