Controllers/AdminClothingController.cs
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System;
using Camisetas.Infrastructure.Filters;
using Camisetas.Infrastructure;
using Camisetas.Models.ViewModels;
using Camisetas.Models;
using Camisetas.DAL;

namespace Camisetas.Controllers
{
    [RepositoryExceptionFilter]
    public class AdminClothingController : Controller
    {
        // Fields
        private IClothingRepository clothingRepository;
        
        // Ctor
        public AdminClothingController (IClothingRepository repo) 
            => clothingRepository = repo;

        [HttpGet]
        public ViewResult ClothingList(int pageNumber = 1, int itemsPerPage = 4) 
            => View(new GenericListViewModel<Clothing>()
            {
                CollectionToSend = clothingRepository.Clothings
                    .Skip((pageNumber - 1) * itemsPerPage)
                    .Take(itemsPerPage),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = pageNumber,
                    TotalItems = clothingRepository.Clothings.Count(),
                    ItemsPerPage = itemsPerPage
                }
            });

        [HttpGet]
        public ViewResult CreateClothing() => View(new Clothing());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateClothing(
                [FromForm]Clothing clothing)
        {
            if(ModelState.IsValid)
            {
                clothingRepository.SaveClothing(clothing);
                TempData["SuccessMessage"] = 
                    $"{clothing.Name} clothing ({clothing.Id}) "
                    +"was successfully created";
                return View(new Clothing());
            }
            else{ return View(clothing); }
        } // End of method CreateClothing.

        [HttpGet]
        public ViewResult EditClothing(Guid id) =>
            View((clothingRepository[id]) != null ? 
                clothingRepository[id]
                : throw new ArgumentNullException(nameof(id),
                    "Unable to find color to edit") );



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditClothing(Clothing clothing)
        {
            if(ModelState.IsValid)
            {
                clothingRepository.SaveClothing(clothing);
                TempData["SuccessMessage"] = $"{clothing.Name} "
                +$" clothing ({clothing.Id})"
                + " was successfully edited";
                return View(new Clothing());
            }else{
                return View(clothing);
            }
        } // End of method EditClothing.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteClothing([FromForm]Guid clothingId)
        {
            if(clothingId != null)
            {
                Clothing clothing = clothingRepository.DeleteClothing(clothingId);
                if(clothing != null)
                {
                    TempData["SuccessMessage"] = 
                    $"{clothing.Name} ({clothing.Id}) was deleted";
                    return RedirectToAction(nameof(ClothingList));
                }else{
                    TempData["WarningMessage"] = $"Unable to delete {clothingId} ";
                    return RedirectToAction(nameof(ClothingList));
                }
            }else{
                TempData["ErrorMessage"] = 
                    $" Sorry, an unexpected error ocurred when deleting item";
                return RedirectToAction(nameof(ClothingList));
            }
        } // End of method DeleteClothing.

    } // End of class AdminClothingController.
} // End of namespace Camisetas.Controllers.

Views/AdminClothing/ClothingList.cshtml
@model GenericListViewModel<Clothing>

<section class="container" >
    <div class="row text-center ">
        <div class="col-sm-12">
            <div class="table-responsive-sm " >
                <table class="table table-striped table-bordered table-hover " >
                <caption>T-Shirts</caption>
                <thead class="" >
                    <tr scope="row" class="bg-primary"  >
                        <th scope="col" >Id</th> <th scope="col" >Name</th> 
                        <th scope="col" >Actions</th>
                </thead>

                <tbody>
                    @if(Model.CollectionToSend.Count() == 0 )
                    {
                        <tr scope="row" > <td colspan="3" ><p class="text-center" ><b>There is no Clothing to show.</b></p></td> </tr>
                    }else{
                        @foreach(Clothing clothing in Model.CollectionToSend){
                            <tr scope="row" >
                                <td scope="col" >@clothing.Id</td> <td scope="col" >@clothing.Name</td>
                                <td>
                                    <form asp-action="DeleteClothing" asp-controller="AdminClothing" method="POST" >
                                        <a asp-action="EditClothing" style="width:5em;margin-bottom:3px"
                                            asp-controller="AdminClothing" 
                                            asp-route-id="@clothing.Id"
                                            role="button" class="btn btn-sm btn-warning" >
                                            Edit
                                        </a>
                                        <input type="hidden" name="clothingId" asp-for="@clothing.Id" />
                                        <button style="width:5em;" class="btn btn-danger btn-sm" 
                                        type="submit" formmethod="POST" >Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            </div>
        </div>
    </div>
</section>
<section class="container" >
    <div class=" form-group row"> 
        <div class="col-sm-3">
            <a class="custom-margin btn btn-primary" role="button" 
                asp-action="CreateClothing" asp-controller="AdminClothing" >
                Create new Clothing
            </a>
        </div>
        <div class="col-sm-3" >
            <div class="custom-margin btn-group">
                <button class=" btn btn-secondary dropdown-toggle" 
                    type="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Select a page
                </button>
                <div class="dropdown-menu" page-model-links="@Model.PagingInfo" 
                        page-action="ClothingList" >
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <form>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">
                            Current Page
                        </span>
                    </div>
                        <input type="text" class=" text-center form-control" 
                        aria-label="Sizing example input" 
                        aria-describedby="inputGroup-sizing-default"
                        disabled="disabled" value="@Model.PagingInfo.CurrentPage" 
                        />
                </div>
            </form>
        </div>
        <div class="col-sm-3">
            <form>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">
                            Total Items
                        </span>
                    </div>
                        <input type="text" class=" text-center form-control" 
                        aria-label="Sizing example input" 
                        aria-describedby="inputGroup-sizing-default"
                        disabled="disabled" value="@Model.PagingInfo.TotalItems" 
                        />
                </div>
            </form>
        </div>
    </div>
</section>
<section class="container" >
    <div class=" form-group row">
        <div class="col-sm-3 offset-sm-6">
            <form>
                <div class=" custom-margin input-group sm-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">
                            Items Per Page
                        </span>
                    </div>
                        <input type="text" class=" text-center form-control" 
                        aria-label="Sizing example input" 
                        aria-describedby="inputGroup-sizing-default"
                        disabled="disabled" value="@Model.PagingInfo.ItemsPerPage" 
                        />
                </div>
            </form>
        </div>
        <div class="col-sm-3">
            <form>
                <div class="custom-margin input-group sm-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">
                            Total Pages
                        </span>
                    </div>
                        <input type="text" class=" text-center form-control" 
                        aria-label="Sizing example input" 
                        aria-describedby="inputGroup-sizing-default"
                        disabled="disabled" value="@Model.PagingInfo.QtdPages" 
                        />
                </div>
            </form>
        </div>
    </div>
</section>

Views/AdminClothing/CreateAndModifyClothingPartialView.cshtml
@model Clothing

        <div asp-validation-summary="ModelOnly" ></div>
        <div class="row" >
            <div class="col-sm-12 form-group" >
                <label asp-for="@Model.Id" ></label>
                <input readonly="readonly" asp-for="@Model.Id" 
                    class="form-control" />
                <div><span asp-validation-for="@Model.Id" ></span></div>
            </div>
        </div>
        <div class="row" >
            <div class="col-sm-12 form-group" >
                <label asp-for="@Model.Name" ></label>
                <input asp-for="@Model.Name" class="form-control" />
                <div><span asp-validation-for="@Model.Name" ></span></div>
            </div>
        </div>
        <div class="row" >
            <div class="col-sm-2 form-group" >
                <button class="btn btn-primary" formmethod="POST" >
                    Save
                </button>
            </div>
            <div class="col-sm-2 form-group" >
                <a class="btn btn-danger"  asp-controller="AdminClothing" asp-action="ClothingList"
                    role="button" >Cancel</a>
            </div>
        </div>

Views/AdminClothing/CreateClothing.cshtml
@model Clothing

<section class="container" >
    <form asp-action="CreateClothing" asp-controller="AdminClothing" method="POST"  >
        @await Html.PartialAsync("CreateAndModifyClothingPartialView")
    </form>
</section>

Views/AdminClothing/EditClothing.cshtml
@model Clothing

<section class="container" >
    <form asp-action="EditClothing" asp-controller="AdminClothing" method="POST"  >
        @await Html.PartialAsync("CreateAndModifyClothingPartialView")
    </form>
</section>